using Microsoft.Extensions.Logging;
using System.Data;
using System.Data.Common;
using System.Diagnostics;
using System.Linq.Expressions;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Text;

namespace NextORM.Core;

/// <summary>
/// Planning axis of a database-backed context: turns a <see cref="QueryCommand{TResult}"/> into a
/// prepared command (SQL, compiled row mapper, bound parameters) and resolves table sources.
/// Extracted out of <c>DataContext</c> so the context no longer owns the planning algorithm (SRP).
/// Provider hooks (dialect, column-mapping policy, parameter factory) and the connection / logger /
/// enumerator configuration arrive as constructor dependencies, so the planner never sees the
/// concrete context (DIP).
/// </summary>
internal sealed class QueryPlanner : IQueryPlanner
{
    private readonly Func<ISqlDialect> _dialect;
    private readonly ILogger? _logger;
    private readonly Type _contextType;
    private readonly Func<SelectExpression, Expression, Expression> _mapColumn;
    private readonly Func<string, object?, DbParameter> _createParam;
    private readonly Func<string, DbCommand> _createCommand;
    private readonly ILogger? _resultSetEnumeratorLogger;
    private readonly bool _logSensitiveData;

    internal QueryPlanner(
        Func<ISqlDialect> dialect,
        Type contextType,
        ProviderHooks hooks,
        LoggingOptions logging)
    {
        _dialect = dialect;
        _logger = logging.Logger;
        _contextType = contextType;
        _mapColumn = hooks.MapColumn;
        _createParam = hooks.CreateParam;
        _createCommand = hooks.CreateCommand;
        _resultSetEnumeratorLogger = logging.ResultSetEnumeratorLogger;
        _logSensitiveData = logging.LogSensitiveData;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private List<Parameter> ExtractParams(QueryCommand queryCommand)
    {
        var @params = new List<Parameter>();
        MakeSelect(queryCommand, true, @params, queryCommand, null);
        return @params;
    }

    // SqlFunctions.Parameter placeholders carry no value - the runtime values are applied by
    // DbPreparedQueryCommand.GetDbCommand. Only computed parameters (captured variables,
    // closures) need to be re-extracted on every cached execution.
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static bool IsRuntimeParam(string name) => NormParam.IsName(name);

    // Renders a standalone SELECT (the source of an INSERT ... SELECT) to SQL plus its parameters, and
    // hoists any CTE the source declares out of the SELECT. A data-modifying CTE must sit at the top
    // level of the statement, so the caller places WithSql before "insert into"; a plain read CTE is
    // hoisted the same way. The WITH and the SELECT share one parameter provider so the numbering matches
    // the emitted SQL. Runtime SqlFunctions.Parameter placeholders cannot be bound through a mutation
    // command, so they are rejected with an actionable message.
    internal (string? WithSql, string Sql, List<Parameter> Parameters) RenderSource(QueryCommand source)
        => RenderSource(source, null, null, null);

    // Renders the source with a SELECT ... INTO clause injected into the top-level select list (SQL Server
    // CTAS). Only the outer select carries it; CTE, UNION and derived-table bodies render without it.
    internal (string? WithSql, string Sql, List<Parameter> Parameters) RenderSource(QueryCommand source, string? selectInto)
        => RenderSource(source, null, null, selectInto);

    // Overload used by a full MERGE so the source body, the match/branch conditions and the VALUES rows
    // share one parameter provider and accumulator (otherwise their autogenerated names would collide).
    internal (string? WithSql, string Sql, List<Parameter> Parameters) RenderSource(QueryCommand source, IParameterProvider? parameterProvider, List<Parameter>? parameters, string? selectInto = null)
    {
        if (!source.IsPrepared)
            source.PrepareCommand(false, CancellationToken.None);

        var @params = parameters ?? new List<Parameter>();
        var ctx = new SqlBuildContext
        {
            Dialect = _dialect(),
            ParamMode = false,
            Params = @params,
            ColumnsProvider = new DefaultColumnsProvider(),
            QueryProvider = source,
            ParameterProvider = parameterProvider ?? new DefaultParameterProvider(),
            AliasProvider = new DefaultAliasProvider(),
            Logger = _logger!,
            QuoteIdentifiers = source.ResolvedQuoteIdentifiers,
            NamingConvention = source.ResolvedNamingConvention,
            KeywordCase = source.ResolvedKeywordCase,
        };

        string? withSql = null;
        var body = source;
        if (source.Ctes is { Count: > 0 } ctes)
        {
            withSql = SqlSourceRenderer.MakeWithClause(in ctx, ctes, out _);

            body = source.CloneForCache();
            body.Ctes = null;
            ctx = ctx with { QueryProvider = body };
        }

        var sql = new SqlBuilder(in ctx).MakeSelect(body, selectInto);

        for (var i = 0; i < @params.Count; i++)
        {
            if (NormParam.IsName(@params[i].Name))
                throw new NotSupportedException(
                    "An INSERT ... SELECT source cannot use SqlFunctions.Parameter runtime placeholders; capture the value in a local variable instead.");
        }

        return (withSql, sql!, @params);
    }

    // Renders the WHERE predicate of a command as a standalone, unqualified condition, used by
    // DELETE FROM <table> WHERE <condition>. The command is prepared first so the condition matches
    // the SELECT pipeline (captured values become parameters, correlated subqueries are rewritten);
    // only the condition is rendered - no FROM or select list.
    internal (string Sql, List<Parameter> Parameters) RenderPredicate(QueryCommand command)
        => RenderPredicate(command, null, null);

    // Overload used by UPDATE so the WHERE parameters continue the sequence started by the SET list
    // (a fresh provider/list would restart parameter numbering and collide with the SET parameters).
    internal (string Sql, List<Parameter> Parameters) RenderPredicate(QueryCommand command, IParameterProvider? parameterProvider, List<Parameter>? parameters)
    {
        if (!command.IsPrepared)
            command.PrepareCommand(false, CancellationToken.None);

        var @params = parameters ?? new List<Parameter>();
        if (command.PreparedCondition is null)
            return (string.Empty, @params);

        var ctx = new SqlBuildContext
        {
            Dialect = _dialect(),
            ParamMode = false,
            Params = @params,
            ColumnsProvider = new DefaultColumnsProvider(),
            QueryProvider = command,
            ParameterProvider = parameterProvider ?? new DefaultParameterProvider(),
            AliasProvider = new DefaultAliasProvider(),
            Logger = _logger!,
            QuoteIdentifiers = command.ResolvedQuoteIdentifiers,
            NamingConvention = command.ResolvedNamingConvention,
            KeywordCase = command.ResolvedKeywordCase,
        };
        ctx.ColumnsProvider.Add(command.EntityType!, false);

        var builder = new StringBuilder();
        SqlSourceRenderer.MakeWhere(in ctx, builder, command.EntityType!, command.PreparedCondition, 0, dontNeedAlias: true);
        return (builder.ToString(), @params);
    }

    // Renders an ON/AND search condition of a full MERGE over the (target, source) row. The two lambda
    // parameters map to the literal aliases "target"/"source" (via MergeAliasProvider); the condition's
    // parameters join the same accumulator as the MERGE's VALUES rows and branch conditions.
    internal string RenderMergeCondition(
        LambdaExpression condition,
        Type entityType,
        IQueryRegistry registry,
        IParameterProvider parameterProvider,
        List<Parameter> parameters,
        bool quoteIdentifiers,
        INamingConvention? namingConvention,
        KeywordCase keywordCase)
    {
        var ctx = new SqlBuildContext
        {
            Dialect = _dialect(),
            ParamMode = false,
            Params = parameters,
            ColumnsProvider = new DefaultColumnsProvider(),
            QueryProvider = registry,
            ParameterProvider = parameterProvider,
            AliasProvider = MergeAliasProvider.Instance,
            Logger = _logger!,
            QuoteIdentifiers = quoteIdentifiers,
            NamingConvention = namingConvention,
            KeywordCase = keywordCase,
        };

        ctx.ColumnsProvider.Add(entityType, false);
        ctx.ColumnsProvider.Add(entityType, false);
        ctx.ColumnsProvider.PushScope(condition.Parameters);

        try
        {
            var builder = new StringBuilder();
            SqlSourceRenderer.MakeWhere(in ctx, builder, entityType, condition.Body, 1);
            return builder.ToString();
        }
        finally
        {
            ctx.ColumnsProvider.PopScope();
        }
    }

    // Renders the SET list of an UPDATE command (without the SET keyword) together with its parameters.
    // A constant RHS is bound as a parameter, a column RHS renders an unqualified column reference, and
    // an arbitrary RHS expression is rendered by the same column visitor the SELECT/WHERE pipeline uses,
    // so captured variables become parameters and mapped members become quoted columns. The provider and
    // parameter list are shared with the WHERE renderer so names and numbering stay contiguous.
    internal (string SetSql, List<Parameter> Parameters) RenderAssignments(
        UpdateCommand command,
        IParameterProvider parameterProvider,
        List<Parameter> parameters)
    {
        var source = command.Source;
        if (!source.IsPrepared)
            source.PrepareCommand(false, CancellationToken.None);

        var quoteIdentifiers = source.ResolvedQuoteIdentifiers;
        var namingConvention = source.ResolvedNamingConvention;

        var ctx = new SqlBuildContext
        {
            Dialect = _dialect(),
            ParamMode = false,
            Params = parameters,
            ColumnsProvider = new DefaultColumnsProvider(),
            QueryProvider = source,
            ParameterProvider = parameterProvider,
            AliasProvider = new DefaultAliasProvider(),
            Logger = _logger!,
            QuoteIdentifiers = quoteIdentifiers,
            NamingConvention = namingConvention,
            KeywordCase = source.ResolvedKeywordCase,
        };
        ctx.ColumnsProvider.Add(command.EntityType!, false);

        var builder = new StringBuilder();
        for (var i = 0; i < command.Assignments.Count; i++)
        {
            if (i > 0)
                builder.Append(", ");

            var assignment = command.Assignments[i];
            builder.Append(SqlMutationBuilder.RenderColumnReference(ctx.Dialect, quoteIdentifiers, assignment.Property, namingConvention));
            builder.Append(" = ");

            switch (assignment.Kind)
            {
                case UpdateValueKind.Constant:
                    var name = parameterProvider.GetParamName();
                    parameters.Add(new Parameter(name, assignment.Constant));
                    builder.Append(ctx.Dialect.MakeParam(name));
                    break;
                case UpdateValueKind.Column:
                    builder.Append(SqlMutationBuilder.RenderColumnReference(ctx.Dialect, quoteIdentifiers, assignment.Column!, namingConvention));
                    break;
                default:
                    using (var visitor = ctx.CreateColumnVisitor(command.EntityType!, 0, dontNeedAlias: true))
                    {
                        visitor.Visit(assignment.Expression!);
                        visitor.WriteTo(builder);
                    }
                    break;
            }
        }

        return (builder.ToString(), parameters);
    }

    // Renders a multi-table DELETE: the target is the first table of the prepared joined command, whose
    // joins and condition are rendered through the same source/condition pipeline as a SELECT, so aliases
    // and parameters match the equivalent read query.
    internal (string Sql, List<Parameter> Parameters) RenderDeleteJoin(DeleteJoinCommand command)
    {
        var source = command.Source;
        if (!source.IsPrepared)
            source.PrepareCommand(false, CancellationToken.None);

        var @params = new List<Parameter>();
        var ctx = new SqlBuildContext
        {
            Dialect = _dialect(),
            ParamMode = false,
            Params = @params,
            ColumnsProvider = new DefaultColumnsProvider(),
            QueryProvider = source,
            ParameterProvider = new DefaultParameterProvider(),
            AliasProvider = new DefaultAliasProvider(),
            Logger = _logger!,
            QuoteIdentifiers = source.ResolvedQuoteIdentifiers,
            NamingConvention = source.ResolvedNamingConvention,
            KeywordCase = source.ResolvedKeywordCase,
        };

        string? withSql = null;
        string? maxRecursionStmt = null;
        if (source.Ctes is { Count: > 0 } ctes)
            withSql = SqlSourceRenderer.MakeWithClause(in ctx, ctes, out maxRecursionStmt);

        var (sql, parameters) = new SqlBuilder(in ctx).MakeDeleteJoin(command);
        if (withSql is not null)
            sql = withSql + sql;
        if (maxRecursionStmt is not null)
            sql += " " + maxRecursionStmt;
        return (sql, parameters);
    }

    // Renders a multi-table UPDATE: the target is the first table of the prepared joined command, whose
    // joins and condition are rendered through the same source/condition pipeline as a SELECT, so aliases
    // and parameters match the equivalent read query. The SET list shares the same parameter provider.
    internal (string Sql, List<Parameter> Parameters) RenderUpdateJoin(UpdateJoinCommand command)
    {
        var source = command.Source;
        if (!source.IsPrepared)
            source.PrepareCommand(false, CancellationToken.None);

        var @params = new List<Parameter>();
        var ctx = new SqlBuildContext
        {
            Dialect = _dialect(),
            ParamMode = false,
            Params = @params,
            ColumnsProvider = new DefaultColumnsProvider(),
            QueryProvider = source,
            ParameterProvider = new DefaultParameterProvider(),
            AliasProvider = new DefaultAliasProvider(),
            Logger = _logger!,
            QuoteIdentifiers = source.ResolvedQuoteIdentifiers,
            NamingConvention = source.ResolvedNamingConvention,
            KeywordCase = source.ResolvedKeywordCase,
        };

        string? withSql = null;
        string? maxRecursionStmt = null;
        if (source.Ctes is { Count: > 0 } ctes)
            withSql = SqlSourceRenderer.MakeWithClause(in ctx, ctes, out maxRecursionStmt);

        var (sql, parameters) = new SqlBuilder(in ctx).MakeUpdateJoin(command);
        if (withSql is not null)
            sql = withSql + sql;
        if (maxRecursionStmt is not null)
            sql += " " + maxRecursionStmt;
        return (sql, parameters);
    }

    private string? MakeSelect(QueryCommand queryCommand, bool paramMode, List<Parameter> @params, IQueryRegistry queryProvider, IAliasProvider? aliasProvider)
    {
        var ctx = new SqlBuildContext
        {
            Dialect = _dialect(),
            ParamMode = paramMode,
            Params = @params,
            ColumnsProvider = new DefaultColumnsProvider(),
            QueryProvider = queryProvider,
            ParameterProvider = new DefaultParameterProvider(),
            AliasProvider = aliasProvider,
            Logger = _logger!,
            QuoteIdentifiers = queryCommand.ResolvedQuoteIdentifiers,
            NamingConvention = queryCommand.ResolvedNamingConvention,
            KeywordCase = queryCommand.ResolvedKeywordCase,
        };
        var sqlBuilder = new SqlBuilder(in ctx);
        return sqlBuilder.MakeSelect(queryCommand);
    }

    public IPreparedQueryCommand<TResult> GetPreparedQueryCommand<TResult>(QueryCommand<TResult> queryCommand, bool createEnumerator, bool storeInCache, CancellationToken cancellationToken)
    {
        QueryPlan? queryPlan = null;
        IDbCommandHolder? planCache = null;

        if (!queryCommand.IsPrepared) queryCommand.PrepareCommand(!storeInCache, cancellationToken);
        else queryCommand.RefreshInValuesShape();

        var ext = queryCommand.CustomData as RawSqlOverride;

        if (queryCommand.Cache && storeInCache)
        {
            queryPlan = new QueryPlan(queryCommand, ext?.ManualSql);
            QueryPlanStore.TryGet(_contextType, queryPlan, out planCache);
        }

        if (planCache is null)
        {
            if ((_logger?.IsEnabled(LogLevel.Debug) ?? false) && storeInCache && queryCommand.Cache)
                _logger.LogDebug("Query plan cache miss with hash: {hash}", queryPlan!.GetHashCode());

            var (sql, @params) = ext is null
                ? MakeSelectInternal()
                : (ext.ManualSql, ext.MakeParams?.Invoke());

            Func<IDataRecord, TResult>? map = queryCommand.DocumentMode || (queryCommand.SingleRow && queryCommand.OneColumn)
                ? null
                : GetMapCached(queryCommand, sql);

            var noParams = !(@params?.Count > 0);
            var needsParamRefresh = false;
            if (!noParams)
            {
                var parameterList = @params!;
                for (var i = 0; i < parameterList.Count; i++)
                {
                    var parameter = parameterList[i];
                    if (!IsRuntimeParam(parameter.Name) && !parameter.Stable)
                    {
                        needsParamRefresh = true;
                        break;
                    }
                }
            }

            var dbCommand = _createCommand(sql!);
            if (!noParams)
            {
                var parameterList = @params!;
                for (var i = 0; i < parameterList.Count; i++)
                {
                    var p = parameterList[i];
                    dbCommand.Parameters.Add(_createParam(p.Name, p.Value));
                }
            }

            // Some drivers (ClickHouse) turn CommandBehavior.SingleRow into an extra LIMIT 1. The
            // dialect already renders a limit for a single-row command, so the hint must be dropped
            // there to avoid a duplicated clause.
            var singleRow = queryCommand.SingleRow && _dialect().SupportsCommandBehaviorSingleRow;

            var compiledQuery = new DbPreparedQueryCommand<TResult>(dbCommand, map, new PreparedCommandOptions(singleRow, ext is null ? sql! : null, noParams, needsParamRefresh));

            if (createEnumerator)
            {
                var enumerator = CreateResultSetEnumerator(compiledQuery!);
                compiledQuery.Enumerator = enumerator;
            }

            if (storeInCache && queryCommand.Cache)
            {
                QueryPlanStore.Set(_contextType, queryPlan!.GetCacheVersion(), compiledQuery);
            }

            return compiledQuery;
        }
        else
        {
#if DEBUG
            if (_logger?.IsEnabled(LogLevel.Debug) ?? false) _logger.LogDebug("Query plan cache hit");
#endif

            var compiledQuery = (DbPreparedQueryCommand<TResult>)planCache;

            if (queryCommand.CustomData is RawSqlOverride)
            {
                Debug.Assert(string.IsNullOrEmpty(compiledQuery.SqlStmt), "SqlStmt must be null");
            }
            else if (string.IsNullOrEmpty(compiledQuery.SqlStmt))
            {
                Debug.Fail("SqlStmt must be not null");
            }
            else
            {
                if (!compiledQuery.NoParams && compiledQuery.NeedsParamRefresh)
                {
                    var dbCommandParams = compiledQuery.DbCommandParams;

                    var pp = ExtractParams(queryCommand);
                    for (int i = 0; i < pp.Count; i++)
                    {
                        // Normalize null to DBNull for providers that reject null parameter values.
                        dbCommandParams[i].Value = pp[i].Value ?? DBNull.Value;
                        Debug.Assert(dbCommandParams[i].ParameterName == pp[i].Name, $"ParameterName {dbCommandParams[i].ParameterName} not equals {pp[i].Name}");
                    }
                }
            }

            // A plan can be stored by a buffered terminal (createEnumerator: false) and later requested
            // by a streaming one, so the enumerator has to be created on demand. The plan cache is
            // [ThreadStatic], so this entry is only ever touched by the current thread.
            if (createEnumerator && compiledQuery.Enumerator is null)
                compiledQuery.Enumerator = CreateResultSetEnumerator(compiledQuery);

            return compiledQuery;
        }
        (string?, List<Parameter>) MakeSelectInternal()
        {
            var @params = new List<Parameter>();
            var aliasProvider = new DefaultAliasProvider();
            return (MakeSelect(queryCommand, false, @params, queryCommand, aliasProvider), @params);
        }
    }

    public void ResetPreparation(QueryCommand queryCommand)
    {
        //_clearCache = true;
    }

    // A table source is immutable, so one instance can be shared by every query (and cached plan)
    // that selects from the entity. This removes a small allocation and a metadata lookup per join.
    private static readonly System.Collections.Concurrent.ConcurrentDictionary<Type, FromExpression> _fromCache = new();

    private FromExpression GetFrom(Type t)
    {
        if (_fromCache.TryGetValue(t, out var cached))
            return cached;

        if (DataContextCache.Metadata.TryGetValue(t, out var entity) && !string.IsNullOrEmpty(entity.TableName))
        {
            var from = new FromExpression(entity.TableName, entity.IsTableNameAuto, t.IsInterface);
            _fromCache.TryAdd(t, from);
            return from;
        }

        // Table names come from the entity metadata, registered the first time the entity is
        // materialized (From<T>()/EntityBuilder<T>). Reaching this point means the type was never
        // registered, so a table name cannot be produced.
        throw new BuildSqlCommandException(
            $"Table name is not registered for type {t}. Materialize the entity first (for example with {nameof(DataContextExtensions.From)}<{t.Name}>()) so its metadata is registered.");
    }

    public FromExpression? GetFrom(Type srcType, QueryCommand? queryCommand)
    {
        if (srcType != typeof(TableAlias))
        {
            if (queryCommand?.Joins?.Length > 0 && srcType.IsAssignableTo(typeof(IProjection)))
            {
                var propT1 = srcType.GetProperty("Item1") ?? throw new BuildSqlCommandException($"Projection {srcType} must have Item1 property");

                var f = GetFrom(propT1.PropertyType);

                return f;
            }
            else
                return GetFrom(srcType);
        }
        else
            return null;
    }

    private Func<IDataRecord, TResult> GetMapCached<TResult>(QueryCommand<TResult> queryCommand, string? sql)
    {
        return RowMapperFactory.GetOrBuild(queryCommand, sql, _contextType, _logger, _mapColumn);
    }

    /// <summary>
    /// Creates the streaming enumerator and applies the context's logging configuration to it. The
    /// enumerator receives the logger directly rather than pulling it from the context through a
    /// property, which is what kept the enumerator tied to the concrete <c>DataContext</c>.
    /// </summary>
    private ResultSetEnumerator<TResult> CreateResultSetEnumerator<TResult>(DbPreparedQueryCommand<TResult> compiledQuery)
    {
        var enumerator = new ResultSetEnumerator<TResult>(compiledQuery);
        enumerator.InitEnvironment(_resultSetEnumeratorLogger, _logSensitiveData);
        return enumerator;
    }
}
