<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
    <PackageReference Include="Dapper" />
    <PackageReference Include="linq2db" />
    <PackageReference Include="linq2db.SQLite" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" />
    <PackageReference Include="System.Linq.Async" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\nextorm.core\nextorm.core.csproj" />
    <ProjectReference Include="..\..\src\nextorm.sqlite\nextorm.sqlite.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="data\test.db">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
