<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>nextorm.postgres</PackageId>
    <Title>Nextorm PostgreSQL provider</Title>
    <Description>PostgreSQL provider for Nextorm</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\nextorm.core\nextorm.core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql" />
  </ItemGroup>

  <ItemGroup>
    <None Include="readme.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
