<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>nextorm.mysql</PackageId>
    <Title>Nextorm MySQL provider</Title>
    <Description>MySQL provider for Nextorm</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\nextorm.core\nextorm.core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MySqlConnector" />
  </ItemGroup>

  <ItemGroup>
    <None Include="readme.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
