<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>nextorm.clickhouse</PackageId>
    <Title>Nextorm ClickHouse provider</Title>
    <Description>ClickHouse provider for Nextorm</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\nextorm.core\nextorm.core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClickHouse.Driver" />
  </ItemGroup>

  <ItemGroup>
    <None Include="readme.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
