<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>nextorm.mariadb</PackageId>
    <Title>Nextorm MariaDB provider</Title>
    <Description>MariaDB provider for Nextorm</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\nextorm.mysql\nextorm.mysql.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="readme.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
