<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>nextorm.sqlite</PackageId>
    <Title>Nextorm SQLite provider</Title>
    <Description>SQLite provider for Nextorm</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\nextorm.core\nextorm.core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" />
  </ItemGroup>

  <ItemGroup>
    <None Include="readme.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
