<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\nextorm.core\nextorm.core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" />
  </ItemGroup>

  <PropertyGroup>
    <PackageId>nextorm.sqlserver</PackageId>
    <Title>Nextorm MS SqlServer provider</Title>
    <Description>Microsoft SQL Server provider for Nextorm</Description>
  </PropertyGroup>
  
  <ItemGroup>
    <None Include="readme.md" Pack="true" PackagePath="\" />
  </ItemGroup>
  
</Project>
