<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>nextorm.examples.clickhouse.analytics</AssemblyName>
    <RootNamespace>NextORM.Examples.ClickHouse.Analytics</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClickHouse.Driver" />
    <PackageReference Include="nextorm" />
    <PackageReference Include="nextorm.clickhouse" />
    <PackageReference Include="Testcontainers.ClickHouse" />
  </ItemGroup>

</Project>
