<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>nextorm.examples.clickhouse.analytics</AssemblyName>
    <RootNamespace>NextORM.Examples.ClickHouse.Analytics</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClickHouse.Driver" />
    <PackageReference Include="Testcontainers.ClickHouse" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\nextorm.core\nextorm.core.csproj" />
    <ProjectReference Include="..\..\src\nextorm.clickhouse\nextorm.clickhouse.csproj" />
  </ItemGroup>

</Project>
