# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install apt packages
        run: sudo apt-get install tree
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: copy database
        run: cp -f nextorm.sqlite.tests/data/test.db nextorm.sqlite.tests/bin/Debug/net7.0/data
      - name: list files
        run: tree --du -h nextorm.sqlite.tests
      - name: Test
        run: dotnet test --no-build --verbosity normal
